name: 'Build Notifier'
description: 'This GitHub Action will allow you to take data and send it somewhere.'
branding:
  icon: 'check'
  color: 'gray-dark'

inputs:
  input:
    description: 'The JSON user input'
    required: true
  url:
    description: 'The endpoint URL'
    required: true
outputs:
  success:
    description: 'Indicates if the data was sent successfully'

runs:
  using: 'node20'
  main: './dist/index.js'
